<?php

// $Author: wishcraft $
//  ------------------------------------------------------------------------ //
//                XOOPS - PHP Content Management System                      //
//                    Copyright (c) 2000 XOOPS.org                           //
//                       <http://www.xoops.org/>                             //
//  ------------------------------------------------------------------------ //
//  This program is free software; you can redistribute it and/or modify     //
//  it under the terms of the GNU General Public License as published by     //
//  the Free Software Foundation; either version 2 of the License, or        //
//  (at your option) any later version.                                      //
//                                                                           //
//  You may not change or alter any portion of this comment or credits       //
//  of supporting developers from this source code or any supporting         //
//  source code which is considered copyrighted (c) material of the          //
//  original comment or credit authors.                                      //
//                                                                           //
//  This program is distributed in the hope that it will be useful,          //
//  but WITHOUT ANY WARRANTY; without even the implied warranty of           //
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the            //
//  GNU General Public License for more details.                             //
//                                                                           //
//  You should have received a copy of the GNU General Public License        //
//  along with this program; if not, write to the Free Software              //
//  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA //
//  ------------------------------------------------------------------------ //
// Author: Simon Roberts (AKA wishcraft)                                     //
// URL: http://www.chronolabs.org.au                                         //
// Project: The XOOPS Project                                                //
// ------------------------------------------------------------------------- //

$modversion['name'] = _MI_BITLY_NAME;
$modversion['version'] = 1.01;
$modversion['releasedate'] = "Friday, May 25, 2012";
$modversion['description'] = _MI_BITLY_DESCRIPTION;
$modversion['author'] = "Wishcraft";
$modversion['credits'] = "Simon Roberts (simon@chronolabs.coop)";
$modversion['help'] = "bitlybomb.html";
$modversion['license'] = "GPL 3.0";
$modversion['official'] = 0;
$modversion['module_status']  = "Stable";
$modversion['image'] = "images/bitlybomb_slogo.png";
$modversion['dirname'] = _MI_BITLY_DIRNAME;
$modversion['hasMain'] = 1;
$modversion['website'] = "www.chronolabs.com.au";

$modversion['dirmoduleadmin'] = 'Frameworks/moduleclasses';
$modversion['icons16'] = 'Frameworks/moduleclasses/icons/16';
$modversion['icons32'] = 'Frameworks/moduleclasses/icons/32';

$modversion['release_info'] = "Stable 2012/05/25";
$modversion['release_file'] = XOOPS_URL."/modules/twitterbomb/docs/changelog.txt";
$modversion['release_date'] = "2012/05/25";

$modversion['author_realname'] = "Simon Antony Roberts";
$modversion['author_website_url'] = "http://www.chronolabs.com.au";
$modversion['author_website_name'] = "Chronolabs Australia";
$modversion['author_email'] = "simon@chronolabs.com.au";
$modversion['demo_site_url'] = "Chronolabs Pty Ltd";
$modversion['demo_site_name'] = "";
$modversion['support_site_url'] = "";
$modversion['support_site_name'] = "Chronolabs";
$modversion['submit_bug'] = "";
$modversion['submit_feature'] = "";
$modversion['usenet_group'] = "sci.chronolabs";
$modversion['maillist_announcements'] = "";
$modversion['maillist_bugs'] = "";
$modversion['maillist_features'] = "";

$modversion['system_menu'] = 1;

// Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = "admin/dashboard.php";
$modversion['adminmenu'] = "admin/menu.php";

//$modversion['onUpdate'] = "include/update.php";
//$modversion['onInstall'] = "include/install.php";
//$modversion['onUninstall'] = "include/uninstall.php";

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = "sql/mysql.sql";

// $modversion['sqlfile']['postgresql'] = "sql/pgsql.sql";
// Tables created by sql file (without prefix!)
$i=0;
$modversion['tables'][++$i] = "bitly_oauth";
$modversion['tables'][++$i] = "bitly_shorten";
$modversion['tables'][++$i] = "bitly_referrers";
$modversion['tables'][++$i] = "bitly_countries";
$modversion['tables'][++$i] = "bitly_byminute";
$modversion['tables'][++$i] = "bitly_byday";
$modversion['tables'][++$i] = "bitly_userclicks";
$modversion['tables'][++$i] = "bitly_userclicks_clicks";
$modversion['tables'][++$i] = "bitly_userreferrers";
$modversion['tables'][++$i] = "bitly_userreferrers_clicks";
$modversion['tables'][++$i] = "bitly_usercountries";
$modversion['tables'][++$i] = "bitly_usercountries_clicks";
$modversion['tables'][++$i] = "bitly_userrealtimelinks";

// Blocks
$modversion['blocks'][1]['file'] = "bitly_user_realtime_links.php";
$modversion['blocks'][1]['name'] = 'Most popular links' ;
$modversion['blocks'][1]['description'] = "most popular links based on click traffic in the past hour";
$modversion['blocks'][1]['show_func'] = "b_bitly_block_user_realtime_links_show";
$modversion['blocks'][1]['edit_func'] = "b_bitly_block_user_realtime_links_edit";
$modversion['blocks'][1]['options'] = "10";
$modversion['blocks'][1]['template'] = "bitly_block_user_realtime_links.html" ;

// Templates
$i=0;
/*$i++;
$modversion['templates'][$i]['file'] = 'BITLYbomb_cpanel_email_list.html';
$modversion['templates'][$i]['description'] = 'Template for Retrieving Email Address from User';
$i++;
$modversion['templates'][$i]['file'] = 'BITLYbomb_cpanel_filter_default.html';
$modversion['templates'][$i]['description'] = 'Template for Retrieving Email Address from User';
$i++;
$modversion['templates'][$i]['file'] = 'BITLYbomb_cpanel_ims_list.html';
$modversion['templates'][$i]['description'] = 'Template for Retrieving Email Address from User';
$i++;
$modversion['templates'][$i]['file'] = 'BITLYbomb_cpanel_persons_list.html';
$modversion['templates'][$i]['description'] = 'Template for Retrieving Email Address from User';
$i++;
$modversion['templates'][$i]['file'] = 'BITLYbomb_cpanel_phones_list.html';
$modversion['templates'][$i]['description'] = 'Template for Retrieving Email Address from User';
$i++;
$modversion['templates'][$i]['file'] = 'BITLYbomb_cpanel_profiles_list.html';
$modversion['templates'][$i]['description'] = 'Template for Retrieving Email Address from User';
$i++;
$modversion['templates'][$i]['file'] = 'BITLYbomb_cpanel_providers_list.html';
$modversion['templates'][$i]['description'] = 'Template for Retrieving Email Address from User';
$i++;
$modversion['templates'][$i]['file'] = 'BITLYbomb_get_email.html';
$modversion['templates'][$i]['description'] = 'Template for Retrieving Email Address from User';
$i++;
$modversion['templates'][$i]['file'] = 'BITLYbomb_profile.html';
$modversion['templates'][$i]['description'] = 'Template for Retrieving Email Address from User';
*/

// Menu

$i = 0;
$i++;
$modversion['config'][$i]['name'] = 'sanitizer';
$modversion['config'][$i]['title'] = '_MI_BITLY_SANITIZER';
$modversion['config'][$i]['description'] = '_MI_BITLY_SANITIZER_DESC';
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = true;

$i++;
$modversion['config'][$i]['name'] = 'crawlnext';
$modversion['config'][$i]['title'] = '_MI_BITLY_CRAWLNEXT';
$modversion['config'][$i]['description'] = '_MI_BITLY_CRAWLNEXT_DESC';
$modversion['config'][$i]['formtype'] = 'select';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = (60*60*24*7);
$modversion['config'][$i]['options'] = array(_MI_BITLY_TIME_30MINUTES => (60*30), _MI_BITLY_TIME_1HOURS => (60*60*1), _MI_BITLY_TIME_2HOURS => (60*60*2),
											 _MI_BITLY_TIME_3HOURS => (60*60*3), _MI_BITLY_TIME_6HOURS => (60*60*6), _MI_BITLY_TIME_12HOURS => (60*60*12),
											 _MI_BITLY_TIME_24HOURS => (60*60*24), _MI_BITLY_TIME_1WEEK => (60*60*24*7), _MI_BITLY_TIME_FORTNIGHT => (60*60*24*7*2), 
											 _MI_BITLY_TIME_1MONTH => (60*60*24*7*4*1), _MI_BITLY_TIME_2MONTHS => (60*60*24*7*4*2), _MI_BITLY_TIME_3MONTHS => (60*60*24*7*4*3), 
											 _MI_BITLY_TIME_4MONTHS => (60*60*24*7*4*4), _MI_BITLY_TIME_5MONTHS => (60*60*24*7*4*5), _MI_BITLY_TIME_6MONTHS => (60*60*24*7*4*6),
											 _MI_BITLY_TIME_12MONTHS => (60*60*24*7*4*12), _MI_BITLY_TIME_24MONTHS => (60*60*24*7*4*24));

$i++;
$modversion['config'][$i]['name'] = 'links_kept';
$modversion['config'][$i]['title'] = '_MI_BITLY_REALTIME_LINKS_KEPT';
$modversion['config'][$i]['description'] = '_MI_BITLY_REALTIME_LINKS_KEPT_DESC';
$modversion['config'][$i]['formtype'] = 'select';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = (60*60*3);
$modversion['config'][$i]['options'] = array(_MI_BITLY_TIME_30MINUTES => (60*30), _MI_BITLY_TIME_1HOURS => (60*60*1), _MI_BITLY_TIME_2HOURS => (60*60*2),
											 _MI_BITLY_TIME_3HOURS => (60*60*3), _MI_BITLY_TIME_6HOURS => (60*60*6), _MI_BITLY_TIME_12HOURS => (60*60*12),
											 _MI_BITLY_TIME_24HOURS => (60*60*24), _MI_BITLY_TIME_1WEEK => (60*60*24*7), _MI_BITLY_TIME_FORTNIGHT => (60*60*24*7*2), 
											 _MI_BITLY_TIME_1MONTH => (60*60*24*7*4*1), _MI_BITLY_TIME_2MONTHS => (60*60*24*7*4*2), _MI_BITLY_TIME_3MONTHS => (60*60*24*7*4*3), 
											 _MI_BITLY_TIME_4MONTHS => (60*60*24*7*4*4), _MI_BITLY_TIME_5MONTHS => (60*60*24*7*4*5), _MI_BITLY_TIME_6MONTHS => (60*60*24*7*4*6),
											 _MI_BITLY_TIME_12MONTHS => (60*60*24*7*4*12), _MI_BITLY_TIME_24MONTHS => (60*60*24*7*4*24));
	
$i++;
$modversion['config'][$i]['name'] = 'limitoncrawl';
$modversion['config'][$i]['title'] = "_MI_BITLY_LIMIT_ON_CRAWL";
$modversion['config'][$i]['description'] = "_MI_BITLY_LIMIT_ON_CRAWL_DESC";
$modversion['config'][$i]['formtype'] = 'text';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = '10';
											 
$i++;
$modversion['config'][$i]['name'] = 'crawlsort';
$modversion['config'][$i]['title'] = "_MI_BITLY_CRAWL_SORT";
$modversion['config'][$i]['description'] = "_MI_BITLY_CRAWL_SORT_DESC";
$modversion['config'][$i]['formtype'] = 'select';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = 'RAND()';
$modversion['config'][$i]['options'] = array(_MI_BITLY_CRAWL_SORT_RANDOM => 'RAND()', _MI_BITLY_CRAWL_SORT_CREATED => '`created`', _MI_BITLY_CRAWL_SORT_UPDATED => '`updated`',
											 _MI_BITLY_CRAWL_SORT_EXPIRES => '`expires`', _MI_BITLY_CRAWL_SORT_CRAWLED => '`crawled`');
$i++;
$modversion['config'][$i]['name'] = 'crawlorder';
$modversion['config'][$i]['title'] = "_MI_BITLY_CRAWL_ORDER";
$modversion['config'][$i]['description'] = "_MI_BITLY_CRAWL_ORDER_DESC";
$modversion['config'][$i]['formtype'] = 'select';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = 'DESC';
$modversion['config'][$i]['options'] = array(_MI_BITLY_CRAWL_ORDER_DESC => 'DESC', _MI_BITLY_CRAWL_ORDER_ASC => 'ASC');

$i++;
$modversion['config'][$i]['name'] = 'client_id';
$modversion['config'][$i]['title'] = "_MI_BITLY_CLIENT_ID";
$modversion['config'][$i]['description'] = "_MI_BITLY_CLIENT_ID_DESC";
$modversion['config'][$i]['formtype'] = 'text';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = '';

$i++;
$modversion['config'][$i]['name'] = 'client_secret';
$modversion['config'][$i]['title'] = "_MI_BITLY_CLIENT_SECRET";
$modversion['config'][$i]['description'] = "_MI_BITLY_CLIENT_SECRET_DESC";
$modversion['config'][$i]['formtype'] = 'password';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = '';

$i++;
$modversion['config'][$i]['name'] = 'domain';
$modversion['config'][$i]['title'] = "_MI_BITLY_DOMAIN";
$modversion['config'][$i]['description'] = "_MI_BITLY_DOMAIN_DESC";
$modversion['config'][$i]['formtype'] = 'select';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = 'bit.ly';
$modversion['config'][$i]['options'] = array(_MI_BITLY_DOMAIN_BITLY_DESC => 'bit.ly', _MI_BITLY_DOMAIN_JMP_DESC => 'j.mp', _MI_BITLY_DOMAIN_OTHER_DESC => '----');

$i++;
$modversion['config'][$i]['name'] = 'other_domain';
$modversion['config'][$i]['title'] = "_MI_BITLY_OTHER_DOMAIN";
$modversion['config'][$i]['description'] = "_MI_BITLY_OTHER_DOMAIN_DESC";
$modversion['config'][$i]['formtype'] = 'text';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = '';

$i++;
$modversion['config'][$i]['name'] = 'callback_url';
$modversion['config'][$i]['title'] = "_MI_BITLY_CALLBACK_URL";
$modversion['config'][$i]['description'] = "_MI_BITLY_CALLBACK_URL_DESC";
$modversion['config'][$i]['formtype'] = 'text';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = XOOPS_URL.'/modules/bitly/callback/';

$i++;
$modversion['config'][$i]['name'] = 'user_agent';
$modversion['config'][$i]['title'] = "_MI_BITLY_USER_AGENT";
$modversion['config'][$i]['description'] = "_MI_BITLY_USER_AGENT_DESC";
$modversion['config'][$i]['formtype'] = 'text';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = 'Mozilla/5.0 ('.XOOPS_VERSION.'; cURL; PHP '.PHP_VERSION.') Bit.ly/XOOPS/'.$modversion['version'];

$i++;
$modversion['config'][$i]['name'] = 'curl_connect_timeout';
$modversion['config'][$i]['title'] = "_MI_BITLY_CURL_CONNECT_TIMEOUT";
$modversion['config'][$i]['description'] = "_MI_BITLY_CURL_CONNECT_TIMEOUT_DESC";
$modversion['config'][$i]['formtype'] = 'text';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 30;

$i++;
$modversion['config'][$i]['name'] = 'curl_timeout';
$modversion['config'][$i]['title'] = "_MI_BITLY_CURL_TIMEOUT";
$modversion['config'][$i]['description'] = "_MI_BITLY_CURL_TIMEOUT_DESC";
$modversion['config'][$i]['formtype'] = 'text';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 30;

$i++;
$modversion['config'][$i]['name'] = 'crontype';
$modversion['config'][$i]['title'] = '_MI_BITLY_CRONTYPE';
$modversion['config'][$i]['description'] = '_MI_BITLY_CRONTYPE_DESC';
$modversion['config'][$i]['formtype'] = 'select';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = 'preloader';
$modversion['config'][$i]['options'] = 	array(	_MI_BITLY_CRONTYPE_PRELOADER => 'preloader', 
												_MI_BITLY_CRONTYPE_CRONTAB => 'crontab', 
												_MI_BITLY_CRONTYPE_SCHEDULER => 'scheduler'
										);

$i++;
$modversion['config'][$i]['name'] = 'interval_of_cron';
$modversion['config'][$i]['title'] = "_MI_BITLY_INTERVAL_OF_CRON";
$modversion['config'][$i]['description'] = "_MI_BITLY_INTERVAL_OF_CRON_DESC";
$modversion['config'][$i]['formtype'] = 'text';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 60;

$i++;
$modversion['config'][$i]['name'] = 'length_of_cron';
$modversion['config'][$i]['title'] = "_MI_BITLY_LENGTH_OF_CRON";
$modversion['config'][$i]['description'] = "_MI_BITLY_LENGTH_OF_CRON_DESC";
$modversion['config'][$i]['formtype'] = 'text';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 30;

$i++;
$modversion['config'][$i]['name'] = 'cron_crawl';
$modversion['config'][$i]['title'] = '_MI_BITLY_CRON_CRAWL';
$modversion['config'][$i]['description'] = '_MI_BITLY_CRON_CRAWL';
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = true;
$modversion['config'][$i]['options'] = 	array();

$i++;
$modversion['config'][$i]['name'] = 'cron_poll';
$modversion['config'][$i]['title'] = '_MI_BITLY_CRON_POLL';
$modversion['config'][$i]['description'] = '_MI_BITLY_CRON_POLL';
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = true;
$modversion['config'][$i]['options'] = 	array();

mt_srand(microtime(true));
$i++;
$modversion['config'][$i]['name'] = 'salt';
$modversion['config'][$i]['title'] = "_MI_BITLY_SALT";
$modversion['config'][$i]['description'] = "_MI_BITLY_SALT_DESC";
$modversion['config'][$i]['formtype'] = 'text';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = (mt_rand(1,9)!=5?chr(mt_rand(32,190)):'').(mt_rand(1,9)!=5?chr(mt_rand(32,190)):'').(mt_rand(1,9)!=5?chr(mt_rand(32,190)):'').(mt_rand(1,9)!=5?chr(mt_rand(32,190)):'').(mt_rand(1,9)!=5?chr(mt_rand(32,190)):'').(mt_rand(1,9)!=5?chr(mt_rand(32,190)):'').(mt_rand(1,9)!=5?chr(mt_rand(32,190)):'').(mt_rand(1,9)!=5?chr(mt_rand(32,190)):'').(mt_rand(1,9)!=5?chr(mt_rand(32,190)):'').(mt_rand(1,9)!=5?chr(mt_rand(32,190)):'').(mt_rand(1,9)!=5?chr(mt_rand(32,190)):'').(mt_rand(1,9)!=5?chr(mt_rand(32,190)):'').(mt_rand(1,9)!=5?chr(mt_rand(32,190)):'').(mt_rand(1,9)!=5?chr(mt_rand(32,190)):'').(mt_rand(1,9)!=5?chr(mt_rand(32,190)):'').(mt_rand(1,9)!=5?chr(mt_rand(32,190)):'').(mt_rand(1,9)!=5?chr(mt_rand(32,190)):'').(mt_rand(1,9)!=5?chr(mt_rand(32,190)):'').(mt_rand(1,9)!=5?chr(mt_rand(32,190)):'').(mt_rand(1,9)!=5?chr(mt_rand(32,190)):'').(mt_rand(1,9)!=5?chr(mt_rand(32,190)):'').(mt_rand(1,9)!=5?chr(mt_rand(32,190)):'').(mt_rand(1,9)!=5?chr(mt_rand(32,190)):'').(mt_rand(1,9)!=5?chr(mt_rand(32,190)):'').(mt_rand(1,9)!=5?chr(mt_rand(32,190)):'').(mt_rand(1,9)!=5?chr(mt_rand(32,190)):'').(mt_rand(1,9)!=5?chr(mt_rand(32,190)):'').(mt_rand(1,9)!=5?chr(mt_rand(32,190)):'').(mt_rand(1,9)!=5?chr(mt_rand(32,190)):'').(mt_rand(1,9)!=5?chr(mt_rand(32,190)):'').(mt_rand(1,9)!=5?chr(mt_rand(32,190)):'').(mt_rand(1,9)!=5?chr(mt_rand(32,190)):'').(mt_rand(1,9)!=5?chr(mt_rand(32,190)):'').(mt_rand(1,9)!=5?chr(mt_rand(32,190)):'').(mt_rand(1,9)!=5?chr(mt_rand(32,190)):'').(mt_rand(1,9)!=5?chr(mt_rand(32,190)):'').(mt_rand(1,9)!=5?chr(mt_rand(32,190)):'').(mt_rand(1,9)!=5?chr(mt_rand(32,190)):'').(mt_rand(1,9)!=5?chr(mt_rand(32,190)):'').(mt_rand(1,9)!=5?chr(mt_rand(32,190)):'').(mt_rand(1,9)!=5?chr(mt_rand(32,190)):'').(mt_rand(1,9)!=5?chr(mt_rand(32,190)):'').(mt_rand(1,9)!=5?chr(mt_rand(32,190)):'').(mt_rand(1,9)!=5?chr(mt_rand(32,190)):'').(mt_rand(1,9)!=5?chr(mt_rand(32,190)):'').(mt_rand(1,9)!=5?chr(mt_rand(32,190)):'').(mt_rand(1,9)!=5?chr(mt_rand(32,190)):'').(mt_rand(1,9)!=5?chr(mt_rand(32,190)):'').(mt_rand(1,9)!=5?chr(mt_rand(32,190)):'').(mt_rand(1,9)!=5?chr(mt_rand(32,190)):'').(mt_rand(1,9)!=5?chr(mt_rand(32,190)):'').(mt_rand(1,9)!=5?chr(mt_rand(32,190)):'').(mt_rand(1,9)!=5?chr(mt_rand(32,190)):'').(mt_rand(1,9)!=5?chr(mt_rand(32,190)):'').(mt_rand(1,9)!=5?chr(mt_rand(32,190)):'').(mt_rand(1,9)!=5?chr(mt_rand(32,190)):'').(mt_rand(1,9)!=5?chr(mt_rand(32,190)):'').(mt_rand(1,9)!=5?chr(mt_rand(32,190)):'').(mt_rand(1,9)!=5?chr(mt_rand(32,190)):'').(mt_rand(1,9)!=5?chr(mt_rand(32,190)):'').(mt_rand(1,9)!=5?chr(mt_rand(32,190)):'').(mt_rand(1,9)!=5?chr(mt_rand(32,190)):'').(mt_rand(1,9)!=5?chr(mt_rand(32,190)):'').(mt_rand(1,9)!=5?chr(mt_rand(32,190)):'').(mt_rand(1,9)!=5?chr(mt_rand(32,190)):'').(mt_rand(1,9)!=5?chr(mt_rand(32,190)):'').(mt_rand(1,9)!=5?chr(mt_rand(32,190)):'').(mt_rand(1,9)!=5?chr(mt_rand(32,190)):'').(mt_rand(1,9)!=5?chr(mt_rand(32,190)):'').(mt_rand(1,9)!=5?chr(mt_rand(32,190)):'').(mt_rand(1,9)!=5?chr(mt_rand(32,190)):'').(mt_rand(1,9)!=5?chr(mt_rand(32,190)):'').(mt_rand(1,9)!=5?chr(mt_rand(32,190)):'').(mt_rand(1,9)!=5?chr(mt_rand(32,190)):'').(mt_rand(1,9)!=5?chr(mt_rand(32,190)):'').(mt_rand(1,9)!=5?chr(mt_rand(32,190)):'').(mt_rand(1,9)!=5?chr(mt_rand(32,190)):'').(mt_rand(1,9)!=5?chr(mt_rand(32,190)):'').(mt_rand(1,9)!=5?chr(mt_rand(32,190)):'').(mt_rand(1,9)!=5?chr(mt_rand(32,190)):'').(mt_rand(1,9)!=5?chr(mt_rand(32,190)):'').(mt_rand(1,9)!=5?chr(mt_rand(32,190)):'').(mt_rand(1,9)!=5?chr(mt_rand(32,190)):'').(mt_rand(1,9)!=5?chr(mt_rand(32,190)):'').(mt_rand(1,9)!=5?chr(mt_rand(32,190)):'').(mt_rand(1,9)!=5?chr(mt_rand(32,190)):'').(mt_rand(1,9)!=5?chr(mt_rand(32,190)):'').(mt_rand(1,9)!=5?chr(mt_rand(32,190)):'').(mt_rand(1,9)!=5?chr(mt_rand(32,190)):'').(mt_rand(1,9)!=5?chr(mt_rand(32,190)):'');

$i++;
$modversion['config'][$i]['name'] = 'odds_lower';
$modversion['config'][$i]['title'] = "_MI_BITLY_ODDS_LOWER";
$modversion['config'][$i]['description'] = "_MI_BITLY_ODDS_LOWER_DESC";
$modversion['config'][$i]['formtype'] = 'text';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 0;

$i++;
$modversion['config'][$i]['name'] = 'odds_higher';
$modversion['config'][$i]['title'] = "_MI_BITLY_ODDS_HIGHER";
$modversion['config'][$i]['description'] = "_MI_BITLY_ODDS_HIGHER_DESC";
$modversion['config'][$i]['formtype'] = 'text';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 10;
$i++;
$modversion['config'][$i]['name'] = 'odds_minimum';
$modversion['config'][$i]['title'] = "_MI_BITLY_ODDS_MINIMUM";
$modversion['config'][$i]['description'] = "_MI_BITLY_ODDS_MINIMUM_DESC";
$modversion['config'][$i]['formtype'] = 'text';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 4;

$i++;
$modversion['config'][$i]['name'] = 'odds_maximum';
$modversion['config'][$i]['title'] = "_MI_BITLY_ODDS_MAXIMUM";
$modversion['config'][$i]['description'] = "_MI_BITLY_ODDS_MAXIMUM_DESC";
$modversion['config'][$i]['formtype'] = 'text';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 7;

$i++;
$modversion['config'][$i]['name'] = 'htaccess';
$modversion['config'][$i]['title'] = "_MI_BITLY_HTACCESS";
$modversion['config'][$i]['description'] = "_MI_BITLY_HTACCESS_DESC";
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 0;

$i++;
$modversion['config'][$i]['name'] = 'baseurl';
$modversion['config'][$i]['title'] = "_MI_BITLY_BASEURL";
$modversion['config'][$i]['description'] = "_MI_BITLY_BASEURL_DESC";
$modversion['config'][$i]['formtype'] = 'text';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = 'bitly';

$i++;
$modversion['config'][$i]['name'] = 'endofurl';
$modversion['config'][$i]['title'] = "_MI_BITLY_ENDOFURL";
$modversion['config'][$i]['description'] = "_MI_BITLY_ENDOFURL_DESC";
$modversion['config'][$i]['formtype'] = 'text';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = '.html';

$i++;
$modversion['config'][$i]['name'] = 'endofurl_rss';
$modversion['config'][$i]['title'] = "_MI_BITLY_ENDOFURLRSS";
$modversion['config'][$i]['description'] = "_MI_BITLY_ENDOFURLRSS_DESC";
$modversion['config'][$i]['formtype'] = 'text';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = '.rss';

// Menu
$i=0;
$i++;
$modversion['sub'][$i]['name'] = _MI_BITLY_MENU_SHORTEN_URL;
$modversion['sub'][$i]['url'] = "index.php?op=shorten";

$i++;
$modversion['sub'][$i]['name'] = _MI_BITLY_MENU_POPULAR_RSS;
$modversion['sub'][$i]['url'] = "popular.php";

$oauth_handler = xoops_getmodulehandler('oauth', 'bitly');
if ($oauth_handler->getCount(new Criteria('root', '1'))==0&&!empty($GLOBALS['xoopsModuleConfig']['client_id'])) {
	$i++;
	$modversion['sub'][$i]['name'] = _MI_BITLY_MENU_AUTHORISE_ROOT_USER;
	$modversion['sub'][$i]['url'] = "https://bit.ly/oauth/authorize?client_id=".$GLOBALS['xoopsModuleConfig']['client_id'].'&redirect_uri='.$GLOBALS['xoopsModuleConfig']['callback_url'];
} elseif ($oauth_handler->getCount(new Criteria('root', '1'))==0&&!empty($GLOBALS['xoopsModuleConfig']['client_id'])) {
	$i++;
	$modversion['sub'][$i]['name'] = _MI_BITLY_MENU_AUTHORISE_MY_BITLY;
	$modversion['sub'][$i]['url'] = "https://bit.ly/oauth/authorize?client_id=".$GLOBALS['xoopsModuleConfig']['client_id'].'&redirect_uri='.$GLOBALS['xoopsModuleConfig']['callback_url'];
}
?>
